"""Initial migration

Revision ID: e6fd380d77ec
Revises: 5eb246301f2f
Create Date: 2025-04-25 23:16:34.723498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6fd380d77ec'
down_revision = '5eb246301f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('articles')
    op.drop_table('answers')
    op.drop_table('questions')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product', type_='foreignkey')
        batch_op.drop_constraint('fk_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('courier_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('deliveries_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['courier_id'], ['id'])
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.alter_column('commodity',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('market',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('wholesale_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('retail_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('supply_volume',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_index('idx_market_prices_commodity')
        batch_op.drop_index('idx_market_prices_commodity_id')
        batch_op.drop_index('idx_market_prices_county')
        batch_op.drop_index('idx_market_prices_date')
        batch_op.drop_constraint('unique_market_entry', type_='unique')
        batch_op.drop_column('commodity_id')
        batch_op.drop_column('time_at')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('order_items_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               existing_nullable=True)
        batch_op.drop_constraint('fk_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=postgresql.ENUM('purchase', 'sale', 'other', name='transaction_type'),
               type_=sa.Enum('PURCHASE', 'SALE', 'OTHER', name='transactiontype'),
               existing_nullable=False)
        batch_op.drop_constraint('transactions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('transaction_type',
               existing_type=sa.Enum('PURCHASE', 'SALE', 'OTHER', name='transactiontype'),
               type_=postgresql.ENUM('purchase', 'sale', 'other', name='transaction_type'),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_user', 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('total_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_items_order_id_fkey', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('commodity_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('unique_market_entry', ['commodity_id', 'market', 'date'])
        batch_op.create_index('idx_market_prices_date', ['date'], unique=False)
        batch_op.create_index('idx_market_prices_county', ['county'], unique=False)
        batch_op.create_index('idx_market_prices_commodity_id', ['commodity_id'], unique=False)
        batch_op.create_index('idx_market_prices_commodity', ['commodity'], unique=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('supply_volume',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('retail_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('wholesale_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('market',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('sex',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('commodity',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('deliveries_order_id_fkey', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('courier_id')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_product', 'products', ['product_id'], ['id'], ondelete='CASCADE')

    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('questions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date_asked', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name='questions_farmer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expert_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date_answered', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], name='answers_expert_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='answers_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='answers_pkey')
    )
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='articles_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='articles_pkey')
    )
    op.drop_table('notifications')
    op.drop_table('feedback')
    # ### end Alembic commands ###
